import 'package:cloud_firestore/cloud_firestore.dart';
import '../models/book_model.dart';
import '../services/firestore_service.dart';

class SeedData {
  static final FirestoreService _firestoreService = FirestoreService();

  static List<BookModel> get _sampleBooks => [
        // COMPUTER SCIENCE
        BookModel(
          id: 'cs_1',
          title: 'Introduction to Algorithms',
          author: 'Cormen, Leiserson, Rivest, Stein',
          edition: '3rd Edition',
          conditionRating: 4.5,
          description: 'The standard textbook for algorithms and data structures.',
          price: 45.0,
          exchangePreference: 'Exchange',
          wantedBookTitle: 'Clean Code',
          images: ['https://images.unsplash.com/photo-1516116216624-53e697fedbea?q=80&w=1000&auto=format&fit=crop'],
          sellerId: 'system_seller',
          sellerName: 'Academic Store',
          sellerRating: 5.0,
          status: 'Available',
          createdAt: DateTime.now(),
          category: 'Computer Science',
        ),
        BookModel(
          id: 'cs_2',
          title: 'Clean Code',
          author: 'Robert C. Martin',
          edition: '1st Edition',
          conditionRating: 5.0,
          description: 'A handbook of agile software craftsmanship.',
          price: 30.0,
          exchangePreference: 'Sell',
          images: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?q=80&w=1000&auto=format&fit=crop'],
          sellerId: 'system_seller',
          sellerName: 'Pro Coder',
          sellerRating: 4.8,
          status: 'Available',
          createdAt: DateTime.now(),
          category: 'Computer Science',
        ),
        BookModel(
          id: 'cs_3',
          title: 'Design Patterns',
          author: 'Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides',
          edition: '1st Edition',
          conditionRating: 4.0,
          description: 'Elements of Reusable Object-Oriented Software.',
          price: 40.0,
          exchangePreference: 'Exchange',
          wantedBookTitle: 'Modern Operating Systems',
          images: ['https://images.unsplash.com/photo-1515879218367-8466d910aaa4?q=80&w=1000&auto=format&fit=crop'],
          sellerId: 'system_seller',
          sellerName: 'Design Guru',
          sellerRating: 4.9,
          status: 'Available',
          createdAt: DateTime.now(),
          category: 'Computer Science',
        ),
        BookModel(
          id: 'cs_4',
          title: 'Artificial Intelligence: A Modern Approach',
          author: 'Stuart Russell, Peter Norvig',
          edition: '4th Edition',
          conditionRating: 4.8,
          description: 'Comprehensive overview of AI techniques.',
          price: 55.0,
          exchangePreference: 'Sell',
          images: ['https://images.unsplash.com/photo-1677442136019-21780ecad995?q=80&w=1000&auto=format&fit=crop'],
          sellerId: 'system_seller',
          sellerName: 'AI Explorer',
          sellerRating: 4.7,
          status: 'Available',
          createdAt: DateTime.now(),
          category: 'Computer Science',
        ),
        BookModel(
          id: 'cs_5',
          title: 'The Pragmatic Programmer',
          author: 'Andrew Hunt, David Thomas',
          edition: '20th Anniversary Edition',
          conditionRating: 5.0,
          description: 'Your journey to mastery.',
          price: 35.0,
          exchangePreference: 'Exchange',
          wantedBookTitle: 'Refactoring',
          images: ['https://images.unsplash.com/photo-1498050108023-c5249f4df085?q=80&w=1000&auto=format&fit=crop'],
          sellerId: 'system_seller',
          sellerName: 'Pragmatic Dev',
          sellerRating: 5.0,
          status: 'Available',
          createdAt: DateTime.now(),
          category: 'Computer Science',
        ),

        // IT / INFORMATION TECHNOLOGY
        BookModel(
          id: 'it_1',
          title: 'Computer Networking: A Top-Down Approach',
          author: 'James Kurose, Keith Ross',
          edition: '8th Edition',
          conditionRating: 4.2,
          description: 'Learn networking from the application layer down.',
          price: 50.0,
          exchangePreference: 'Sell',
          images: ['https://images.unsplash.com/photo-1558494949-ef010cbdcc51?q=80&w=1000&auto=format&fit=crop'],
          sellerId: 'system_seller',
          sellerName: 'Network Admin',
          sellerRating: 4.6,
          status: 'Available',
          createdAt: DateTime.now(),
          category: 'IT',
        ),
        BookModel(
          id: 'it_2',
          title: 'CompTIA Security+ Study Guide',
          author: 'Mike Chapple, David Seidl',
          edition: 'SY0-601',
          conditionRating: 5.0,
          description: 'Prepare for the Security+ certification.',
          price: 40.0,
          exchangePreference: 'Exchange',
          wantedBookTitle: 'CEH Certified Ethical Hacker',
          images: ['https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=1000&auto=format&fit=crop'],
          sellerId: 'system_seller',
          sellerName: 'CyberGuard',
          sellerRating: 4.9,
          status: 'Available',
          createdAt: DateTime.now(),
          category: 'IT',
        ),
        BookModel(
          id: 'it_3',
          title: 'Cloud Computing: Concepts, Technology & Architecture',
          author: 'Thomas Erl',
          edition: '1st Edition',
          conditionRating: 4.5,
          description: 'Foundational concepts of cloud computing.',
          price: 45.0,
          exchangePreference: 'Sell',
          images: ['https://images.unsplash.com/photo-1544197150-b99a580bb7a8?q=80&w=1000&auto=format&fit=crop'],
          sellerId: 'system_seller',
          sellerName: 'Cloud Arch',
          sellerRating: 4.8,
          status: 'Available',
          createdAt: DateTime.now(),
          category: 'IT',
        ),
        BookModel(
          id: 'it_4',
          title: 'Linux Bible',
          author: 'Christopher Negus',
          edition: '10th Edition',
          conditionRating: 4.0,
          description: 'The ultimate guide to Linux.',
          price: 38.0,
          exchangePreference: 'Sell',
          images: ['https://images.unsplash.com/photo-1629654297299-c8506221ca97?q=80&w=1000&auto=format&fit=crop'],
          sellerId: 'system_seller',
          sellerName: 'Linux Geek',
          sellerRating: 4.5,
          status: 'Available',
          createdAt: DateTime.now(),
          category: 'IT',
        ),

        // MATH
        BookModel(
          id: 'math_1',
          title: 'Calculus: Early Transcendentals',
          author: 'James Stewart',
          edition: '9th Edition',
          conditionRating: 4.7,
          description: 'Comprehensive calculus textbook.',
          price: 60.0,
          exchangePreference: 'Exchange',
          wantedBookTitle: 'Linear Algebra and Its Applications',
          images: ['https://images.unsplash.com/photo-1635070041078-e363dbe005cb?q=80&w=1000&auto=format&fit=crop'],
          sellerId: 'system_seller',
          sellerName: 'Math Whiz',
          sellerRating: 5.0,
          status: 'Available',
          createdAt: DateTime.now(),
          category: 'Math',
        ),
        BookModel(
          id: 'math_2',
          title: 'Linear Algebra and Its Applications',
          author: 'Gilbert Strang',
          edition: '5th Edition',
          conditionRating: 4.3,
          description: 'Learn linear algebra from a master.',
          price: 42.0,
          exchangePreference: 'Sell',
          images: ['https://images.unsplash.com/photo-1509228468518-180dd4864904?q=80&w=1000&auto=format&fit=crop'],
          sellerId: 'system_seller',
          sellerName: 'Matrix Master',
          sellerRating: 4.8,
          status: 'Available',
          createdAt: DateTime.now(),
          category: 'Math',
        ),
        BookModel(
          id: 'math_3',
          title: 'Discrete Mathematics and Its Applications',
          author: 'Kenneth Rosen',
          edition: '8th Edition',
          conditionRating: 4.5,
          description: 'Fundamental math for CS students.',
          price: 52.0,
          exchangePreference: 'Sell',
          images: ['https://images.unsplash.com/photo-1596495573826-3946d022b4f6?q=80&w=1000&auto=format&fit=crop'],
          sellerId: 'system_seller',
          sellerName: 'Discrete Dr',
          sellerRating: 4.9,
          status: 'Available',
          createdAt: DateTime.now(),
          category: 'Math',
        ),
        BookModel(
          id: 'math_4',
          title: 'Probability and Statistics for Engineers',
          author: 'Walpole, Myers',
          edition: '9th Edition',
          conditionRating: 3.8,
          description: 'Statistical methods for engineering and science.',
          price: 35.0,
          exchangePreference: 'Exchange',
          wantedBookTitle: 'Numerical Analysis',
          images: ['https://images.unsplash.com/photo-1543286386-713bdd548da4?q=80&w=1000&auto=format&fit=crop'],
          sellerId: 'system_seller',
          sellerName: 'Stat Pro',
          sellerRating: 4.4,
          status: 'Available',
          createdAt: DateTime.now(),
          category: 'Math',
        ),

        // PHYSICS
        BookModel(
          id: 'physics_1',
          title: 'University Physics with Modern Physics',
          author: 'Young, Freedman',
          edition: '15th Edition',
          conditionRating: 4.6,
          description: 'Standard textbook for university physics.',
          price: 65.0,
          exchangePreference: 'Sell',
          images: ['https://images.unsplash.com/photo-1636466497217-26a8cbeaf0aa?q=80&w=1000&auto=format&fit=crop'],
          sellerId: 'system_seller',
          sellerName: 'Physics Fan',
          sellerRating: 5.0,
          status: 'Available',
          createdAt: DateTime.now(),
          category: 'Physics',
        ),
        BookModel(
          id: 'physics_2',
          title: 'Fundamentals of Physics',
          author: 'Halliday, Resnick, Walker',
          edition: '11th Edition',
          conditionRating: 4.4,
          description: 'Classic physics textbook for undergraduates.',
          price: 58.0,
          exchangePreference: 'Exchange',
          wantedBookTitle: 'Classical Mechanics',
          images: ['https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1000&auto=format&fit=crop'],
          sellerId: 'system_seller',
          sellerName: 'Quantum Learner',
          sellerRating: 4.7,
          status: 'Available',
          createdAt: DateTime.now(),
          category: 'Physics',
        ),
        BookModel(
          id: 'physics_3',
          title: 'Introduction to Quantum Mechanics',
          author: 'David J. Griffiths',
          edition: '3rd Edition',
          conditionRating: 4.9,
          description: 'Excellent introduction to quantum theory.',
          price: 48.0,
          exchangePreference: 'Sell',
          images: ['https://images.unsplash.com/photo-1614935151651-0bea6508db6b?q=80&w=1000&auto=format&fit=crop'],
          sellerId: 'system_seller',
          sellerName: 'Griffiths Fan',
          sellerRating: 5.0,
          status: 'Available',
          createdAt: DateTime.now(),
          category: 'Physics',
        ),
        BookModel(
          id: 'physics_4',
          title: 'Concepts of Physics (Vol 1 & 2)',
          author: 'H.C. Verma',
          edition: 'Latest Edition',
          conditionRating: 5.0,
          description: 'Highly recommended for understanding basic physics.',
          price: 25.0,
          exchangePreference: 'Sell',
          images: ['https://images.unsplash.com/photo-1444703686981-a3abbc4d4fe3?q=80&w=1000&auto=format&fit=crop'],
          sellerId: 'system_seller',
          sellerName: 'Old School',
          sellerRating: 4.6,
          status: 'Available',
          createdAt: DateTime.now(),
          category: 'Physics',
        ),

        // CHEMISTRY
        BookModel(
          id: 'chem_1',
          title: 'Organic Chemistry',
          author: 'Paula Bruice',
          edition: '8th Edition',
          conditionRating: 4.1,
          description: 'Comprehensive study of carbon compounds.',
          price: 55.0,
          exchangePreference: 'Exchange',
          wantedBookTitle: 'Inorganic Chemistry',
          images: ['https://images.unsplash.com/photo-1532187875605-18038ab03333?q=80&w=1000&auto=format&fit=crop'],
          sellerId: 'system_seller',
          sellerName: 'Chem Catalyst',
          sellerRating: 4.8,
          status: 'Available',
          createdAt: DateTime.now(),
          category: 'Chemistry',
        ),
        BookModel(
          id: 'chem_2',
          title: 'Inorganic Chemistry',
          author: 'Shriver & Atkins',
          edition: '6th Edition',
          conditionRating: 4.3,
          description: 'Depth treatment of inorganic chemistry topics.',
          price: 50.0,
          exchangePreference: 'Sell',
          images: ['https://images.unsplash.com/photo-1603126857599-f6e157fa2fe6?q=80&w=1000&auto=format&fit=crop'],
          sellerId: 'system_seller',
          sellerName: 'Molecule Maker',
          sellerRating: 4.7,
          status: 'Available',
          createdAt: DateTime.now(),
          category: 'Chemistry',
        ),
        BookModel(
          id: 'chem_3',
          title: 'Physical Chemistry',
          author: 'P.W. Atkins',
          edition: '11th Edition',
          conditionRating: 3.9,
          description: 'Principles of chemical kinetics and thermodynamics.',
          price: 62.0,
          exchangePreference: 'Exchange',
          wantedBookTitle: 'Analytical Chemistry',
          images: ['https://images.unsplash.com/photo-1544391682-171738392fd6?q=80&w=1000&auto=format&fit=crop'],
          sellerId: 'system_seller',
          sellerName: 'Science Sage',
          sellerRating: 4.5,
          status: 'Available',
          createdAt: DateTime.now(),
          category: 'Chemistry',
        ),
      ];

  static Future<void> seedBooks() async {
    for (var book in _sampleBooks) {
      // Use Firestore generated ID instead of manual ones to avoid collisions if run multiple times
      final docRef = FirebaseFirestore.instance.collection('books').doc();
      book.id = docRef.id;
      await _firestoreService.addBook(book);
    }
  }
}
